package com.delta.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Foo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String firstName;

	public Foo() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public Foo(java.lang.String firstName) {
		this.firstName = firstName;
	}

}