package com.delta.demo;

rule "Validate Request"
dialect "mvel"
ruleflow-group "validation-grp"

    when
        _foo : Foo( )
        _responseFoo : ResponseFoo ()
    then
        //ResponseFoo responseFoo = new ResponseFoo ();
        //responseFoo.setStatus(100);
        _responseFoo.setStatus(100);
        update(_responseFoo);
        System.out.println ("-->>Successfully Validated");
        
        //kcontext.setVariable("responseFoo", responseFoo);

end