package com.delta.demo;

rule "Validate Request"
dialect "java"
ruleflow-group "validation-grp"
    when
        $foo : Foo( firstName == "nevin" )
    then
        ResponseFoo responseFoo = new ResponseFoo ();
        responseFoo.setStatus(100);
        $foo.setStatus(100);
        System.out.println ("-->>Successfully Validated");
        kcontext.getKieRuntime().insert (responseFoo);
end

rule "Cleaning Up"
dialect "java"
ruleflow-group "cleanup-grp"
    when
        $foo : Foo( firstName == "nevin" )
    then

        System.out.println ("-->>Successfully Clean UP");

end