package com.delta.demo;

rule "Validate Request"
dialect "java"
ruleflow-group 'validation-grp'

    when
        $foo : Foo( firstName == "nevin" )
        $response : ResponseFoo ()
    then
        //ResponseFoo responseFoo = new ResponseFoo ();
        //responseFoo.setStatus(100);
        $response.setStatus(100);
        System.out.println ("-->>Successfully Validated");
        //kcontext.getKieRuntime().insert (responseFoo);

end